#ifndef _GAME_STATE_H_
#define _GAME_STATE_H_

#define GAME_STATE_INIT				0
#define GAME_STATE_PLAYING			1
#define GAME_STATE_CHANGING_ROOM	2
#define GAME_STATE_PAUSING			3
#define GAME_STATE_PAUSED			4
#define GAME_STATE_UNPAUSING		5

#define CHARACTER_PALETTE_INDEX		1
#define ROOM_PALETTE_INDEX			2

#endif // _GAME_STATE_H_
