#ifndef __GUI_H_
#define __GUI_H_

extern const SpriteDefinition gui_hud_lifebar_begin_empty_def;
extern const SpriteDefinition gui_hud_lifebar_begin_filled_def;
extern const SpriteDefinition gui_hud_lifebar_end_empty_def;
extern const SpriteDefinition gui_hud_lifebar_end_filled_def;
extern const SpriteDefinition gui_hud_lifebar_segment_empty_def;
extern const SpriteDefinition gui_hud_lifebar_segment_filled_def;
extern const SpriteDefinition gui_hud_rabbit_def;
extern const SpriteDefinition gui_hud_carrot_def;
extern const SpriteDefinition gui_hud_number_0_def;
extern const SpriteDefinition gui_hud_number_1_def;
extern const SpriteDefinition gui_hud_number_2_def;
extern const SpriteDefinition gui_hud_number_3_def;
extern const SpriteDefinition gui_hud_number_4_def;
extern const SpriteDefinition gui_hud_number_5_def;
extern const SpriteDefinition gui_hud_number_6_def;
extern const SpriteDefinition gui_hud_number_7_def;
extern const SpriteDefinition gui_hud_number_8_def;
extern const SpriteDefinition gui_hud_number_9_def;
extern const TileSet pause_menu_tiles_def;

#endif // __GUI_H_
